### ISSUE TITLE
Link to TS* does not link to the research paper

### ISSUE THREAD

**Issue by DavidBruant** [FStarLang/fstarlang.github.io#1]
In https://www.fstar-lang.org/#introduction

>  and TS*, a secure subset of TypeScript)

There is a link to http://research.microsoft.com/en-us/um/people/nswamy/papers/tstar.pdf
but it redirects to https://www.microsoft.com/en-us/research/people/nswamy/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fpeople%2Fnswamy%2Fpapers%2Ftstar.pdf
and I haven't been able to find the paper from there

**Comment by catalin-hritcu** [comment]
I've pushed fixes for this (and several other broken links), but they haven't yet propagated to the webpage. Will investigate the status of webpage updates is.

**Comment by catalin-hritcu** [comment]
Fixed long time ago
