### ISSUE TITLE
Low* Tutorial Code

### ISSUE THREAD

**Issue by plvines** [FStarLang/fstarlang.github.io#10]
I was attempting to use Low* for a new project and began working through the tutorial here: https://fstarlang.github.io/lowstar/html/Toy.html

However, it is unclear exactly where files should be placed, what they should be named, or how to actually kickoff verifying/building the toy example. Is there a repository backing the tutorial with a complete code tree and Makefiles somewhere? Browsing through some other Fstar and Everest repositories they did not seem to follow the directory/build structure recommended here: https://fstarlang.github.io/lowstar/html/Setup.html#directory-structure

**Comment by msprotz** [comment]
https://github.com/FStarLang/kremlin/tree/master/book/tutorial ?

**Comment by plvines** [comment]
> https://github.com/FStarLang/kremlin/tree/master/book/tutorial ?

Ah, thanks so much! I did not know to look under the kremlin/book repository. I think because the tutorial recommended using everest to install kremlin I never touched the kremlin repo itself.

Perhaps a link to this should be put at the top of this page? https://fstarlang.github.io/lowstar/html/Toy.html

**Comment by msprotz** [comment]
That's a great idea! Let me know if you'd like to submit a PR (you're probably in a better position than I am to write something clear to understand!) or if you'd rather I do it.

Cheers,

Jonathan
